# -*- coding: utf-8 -*-
"""Assignment-1 Deliverable .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OvOdYB_kWa1L_Oxb0_6eOLNtLzS505mP
"""

print('My name is Rajiv Nagesh')

x = input('Enter your name')
y=input('Enter your birthday')
print(x,"is born on",y)

team_list = ['csk', 'mi', 'rcb', 'kxp', 'srh', 'rr', 'dd', 'kkr']
updated_teamlist = [team_list[0],team_list[7],team_list[4],team_list[5]]
print(updated_teamlist)

x = input('Enter your name :')
print(x)
print(len(x))

n=int(input("Enter the number :"))
for i in range(1,21):
  print(n,"*",i,"=",n*i)

num = int(input("Enter a number: "))
if (num % 2) == 0:
  print("{0} is Even number". format(num))
else:
  print("{0} is Odd number". format(num))

a=[34,87,892,920,974,893]
maximum=max(a)
print(maximum)
minimum=min(a)
print(minimum)
sum=sum(a)
length=len(a)
average=sum/length
print(average)

a=[9,56,826,784]
multiplied_list = [element * 5 for element in a]
print(multiplied_list)

student={}

for i in range (2):
  roll_number = input("Enter the roll number : ")
  student_name = input("Enter the student name : ")
  student[roll_number] = student_name
print(student)



def get_dictval(k): 
  return student.get(k)


x=input("Enter the roll number : ")
print(get_dictval(x))